### ISSUE TITLE
Support deletion of Evicted pods

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/governor#33]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
When nodes are drained for reclaiming some resources (e.g. filesystem capacity), the pods that were running on that node are marked `Evicted`. These pods stay in this state unless the node is deleted or the pods are explicitly deleted.

**What you expected to happen**:
Governor should support an option where in it deletes such `Evicted` pods after a certain period of time.

**Comment by eytan-avisror** [comment]
Evicted (failed pods) pods are already supported by using `--reap-failed` and `--reap-failed-after`, however there seem to be a bug preventing specifically evicted pods from getting reaped - this is due to those pods not having containerstatuses and hence no time to compare against.
We should reap failed pods that have no containers as a fix and ignore the time in this case.
